version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-reservation-db
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5441:5432"
    volumes:
      - postgres-reservation-data:/var/lib/postgresql
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d reservation_db"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres-reservation-data:

networks:
  microservices-network:
    driver: bridge
