version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ms-schedule-postgres
    environment:
      POSTGRES_DB: ms_schedule_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - schedule-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ms-schedule:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: ms-schedule-app
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ms_schedule_db
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - schedule-network
  #   restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  schedule-network:
    driver: bridge
