version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: incident_postgres
    environment:
      POSTGRES_DB: incident_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - incident_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: incident_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/incident_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    ports:
      - "8080:8080"
    networks:
      - incident_network

volumes:
  postgres_data:

networks:
  incident_network:
    driver: bridge
