version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: incident_postgres
    environment:
      POSTGRES_DB: incident_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - microservices-network

volumes:
  postgres_data:

networks:
  microservices-network:
    driver: bridge
