version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: inventory-postgres
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventory-network
    restart: unless-stopped

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: inventory-pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@inventory.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - inventory-network
  #   restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  inventory-network:
    driver: bridge
